import Head from 'next/head'
import { Button, LinearProgress } from '@mui/material'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <p>Nextjs Portfolio</p>
        <Button color="primary" variant='outlined'>Update</Button>
      </main>
    </div>
  )
}
